--- #YAML:1.0
name:               WWW-phpBB
version:            0.07
abstract:           phpBB2 forum scraper
author:
    - Stefan Talpalaru <stefantalpalaru@yahoo.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Compress::Zlib:       0
    DBD::mysql:           0
    DBI:                  0
    HTML::TokeParser::Simple:  0
    WWW::Mechanize:       0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
