# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-phpBB
version:      0.02
version_from: lib/WWW/phpBB.pm
installdirs:  site
requires:
    Compress::Zlib:                0
    DBD::mysql:                    0
    DBI:                           0
    HTML::TokeParser::Simple:      0
    WWW::Mechanize:                0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
